version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=metaRainbow
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/metaRainbow"
      AUTH_SECRET: "coolsecret"
      AUTH_URL: "http://localhost:3000"
      ADMIN_NAME: "Admin"
      ADMIN_EMAIL: "admin@metarainbow.com"
      ADMIN_PASSWORD: "admin"
      